@server = http://localhost:4004

### ------------------------------------------------------------------------
# Get service info
GET {{server}}/german-class

### ------------------------------------------------------------------------
# Get $metadata document
GET {{server}}/german-class/$metadata

### ------------------------------------------------------------------------
# Fetch Students as any user
GET {{server}}/german-class/Students?
  &$select=name,lastname,email
  &$expand=pronoun
  &sap-language=de

### ------------------------------------------------------------------------
# Update one Student
PATCH {{server}}/german-class/Students(33081da9-55a3-412a-a178-9ff0aaca1fd1)
Content-Type: application/json;IEEE754Compatible=true

{
    "email"     : "mailchange@mail.com"
}

